sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    access-key-id: xxx
    access-key-secret: xxx
    bucket-name: maoooxiao-learn-oss
    endpoint: oss-cn-shanghai.aliyuncs.com
spring:
  redis:
    host: 120.46.45.8
    port: 6379
    password: 123456
    database: 0
