sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    access-key-id: LTAI5t5dziafLxXdokgi8hB7
    access-key-secret: dAVK0iukHbZ23swfYhuS4D8KrNPQPG
    bucket-name: maoooxiao-learn-oss
    endpoint: oss-cn-shanghai.aliyuncs.com